object Dependencies {
    const val SECURITY_CRYPTO = "androidx.security:security-crypto:${Versions.SECURITY_CRYPTO}"
    const val DATA_STORE = "androidx.datastore:datastore-preferences:${Versions.DATA_STORE}"
    const val INJECT = "javax.inject:javax.inject:${Versions.INJECT}"
    const val LIFECYCLE_COMMON = "androidx.lifecycle:lifecycle-common-java8:${Versions.LIFECYCLE_ANDROIDX}"
    const val KOTLIN_STANDARD_LIBRARY = "org.jetbrains.kotlin:kotlin-stdlib:${Versions.KOTLIN}"
    const val CORE_KTX = "androidx.core:core-ktx:${Versions.KTX}"
    const val HILT_ANDROID = "com.google.dagger:hilt-android:${Versions.HILT_ANDROID}"
    const val LIFECYCLE_VIEW_MODEL_KTX = "androidx.lifecycle:lifecycle-viewmodel-ktx:${Versions.LIFECYCLE_ANDROIDX}"
    const val COROUTINE_CORE = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${Versions.COROUTINES}"
    const val COROUTINE_ANDROID = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Versions.COROUTINES}"
    const val LIFECYCLE_RUNTIME = "androidx.lifecycle:lifecycle-runtime-ktx:${Versions.LIFECYCLE_ANDROIDX}"
    const val ACTIVITY_KTX = "androidx.activity:activity-ktx:${Versions.ACTIVITY_KTX}"
    const val LIFECYCLE_LIVE_DATA = "androidx.lifecycle:lifecycle-livedata-ktx:${Versions.LIFECYCLE_ANDROIDX}"
    const val LIFECYCLE_VIEW_MODEL_SAVE_STATE =  "androidx.lifecycle:lifecycle-viewmodel-savedstate:${Versions.LIFECYCLE_ANDROIDX}"
    const val HILT_VIEW_MODEL_LIFECYCLE = "androidx.hilt:hilt-lifecycle-viewmodel:${Versions.LIFECYCLE_HILT}"
    const val LIFECYCLE_COMPILER = "androidx.lifecycle:lifecycle-compiler:${Versions.LIFECYCLE_ANDROIDX}"
    const val ARCH_CORE_ANDROIDX = "androidx.arch.core:core-runtime:${Versions.ARCH_CORE_RUNTIME}"
    const val SWIPE_REFRESH = "androidx.swiperefreshlayout:swiperefreshlayout:${Versions.SWIPE_REFRESH}"
    const val STURTUP = "androidx.startup:startup-runtime:${Versions.STURTUP}"

    const val RETROFIT = "com.squareup.retrofit2:retrofit:${Versions.RETROFIT}"
    const val RETROFIT_JSON = "com.squareup.retrofit2:converter-gson:${Versions.RETROFIT}"
    const val OK_HTTP_LOGGER = "com.squareup.okhttp3:logging-interceptor:${Versions.OK_HTTP}"
    const val OK_HTTP = "com.squareup.okhttp3:okhttp:${Versions.OK_HTTP}"
    const val APP_COMPAT = "androidx.appcompat:appcompat:${Versions.APP_COMPAT}"

    const val MATERIAL = "com.google.android.material:material:${Versions.MATERIAL}"
    const val CONSTRAINT_LAYOUT =  "androidx.constraintlayout:constraintlayout:${Versions.CONSTRAINT_LAYOUT}"
    const val HILT_ANDROID_COMPILER = "com.google.dagger:hilt-android-compiler:${Versions.HILT_ANDROID}"
    const val HILT_COMPILER = "androidx.hilt:hilt-compiler:${Versions.HILT}"
    const val MAP = "com.google.android.gms:play-services-maps:${Versions.MAP}"
    const val dagger = "com.google.dagger:dagger:${Versions.DAGGER}"
    const val daggerCompiler = "com.google.dagger:dagger-compiler:${Versions.DAGGER}"
    const val ROOM_KTX = "androidx.room:room-ktx:${Versions.ROOM}"
    const val ROOM_COMPILER = "androidx.room:room-compiler:${Versions.ROOM}"
    const val ROOM_RUNTIME = "androidx.room:room-runtime:${Versions.ROOM}"
    const val GREEN_DAO = "org.greenrobot:greendao:${Versions.GREEN_DAO}"
    const val GREEN_DAO_PLUGIN = "org.greenrobot:greendao-gradle-plugin:${Versions.GREEN_DAO_PLUGIN}"
    const val CRYPTO = "androidx.security:security-crypto:${Versions.CRYPTO}"
    const val DEXTER = "com.karumi:dexter:${Versions.DEXTER}"
    const val TIMBER = "com.jakewharton.timber:timber:${Versions.TIMBER}"

    const val NAVIGATION_FRAGMENT = "androidx.navigation:navigation-fragment-ktx:${Versions.NAVIGATION}"
    const val NAVIGATION_UI =  "androidx.navigation:navigation-ui-ktx:${Versions.NAVIGATION}"

    const val ANDROIDX_LEGACY_SUPPORT = "androidx.legacy:legacy-support-v4:${Versions.ANDROIDX_LEGACY_SUPPORT}"
    const val COORDINATOR_LAYOUT = "androidx.coordinatorlayout:coordinatorlayout:${Versions.COORDINATOR_LAYOUT}"

    const val GLIDE = "com.github.bumptech.glide:glide:${Versions.glide}"
    const val GLIDE_COMPILER = "com.github.bumptech.glide:compiler:${Versions.glide}"
    const val MULTIDEX = "androidx.multidex:multidex:${Versions.MULTIDEX}"
    const val VECTOR_DRAWABLE = "androidx.vectordrawable:vectordrawable:${Versions.VECTOR_DRAWABLE}"
    const val BROKER_CODE = "com.github.adrielcafe.broker:broker-core:${Versions.BROKER_CODE}"
    const val BROKER_LIFE_CYCLE = "com.github.adrielcafe.broker:broker-lifecycle:${Versions.BROKER_LIFE_CYCLE}"
    const val FRAGMENT_KTX =  "androidx.fragment:fragment-ktx:${Versions.FRAGMENT_KTX}"
    const val RECYCLER_VIEW =  "androidx.recyclerview:recyclerview:${Versions.RECYCLER_VIEW}"
    const val RX_JAVA =  "io.reactivex.rxjava2:rxjava:${Versions.RX_JAVA}"
    const val RX_ANDROID =  "io.reactivex.rxjava2:rxandroid:${Versions.RX_ANDROID}"
}