object Versions {
    const val FRAGMENT_KTX = "1.3.6"
    const val SECURITY_CRYPTO = "1.0.0"
    const val DATA_STORE = "1.0.0"
    const val INJECT = "1"
    const val COORDINATOR_LAYOUT = "1.1.0"
    const val DEXTER = "6.2.2"

    const val SWIPE_REFRESH = "1.1.0"
    const val STURTUP = "1.0.0"
    const val KTX = "1.6.0"
    const val APP_COMPAT = "1.3.0"
    const val MATERIAL = "1.4.0"
    const val CONSTRAINT_LAYOUT = "2.0.4"
    const val JUNIT = "4.13.1"
    const val EXT_JUNIT = "1.1.2"
    const val ESPRESSO = "3.3.0"
    const val HILT_ANDROID = "2.28-alpha"
    const val HILT = "1.0.0-alpha01"
    const val DAGGER = "2.39.1"
    const val COROUTINES = "1.5.2"
    const val LIFECYCLE_ANDROIDX = "2.3.1"
    const val LIFECYCLE_HILT = "1.0.0"
    const val ACTIVITY_KTX = "1.3.1"
    const val RETROFIT ="2.9.0"
    const val OK_HTTP = "4.9.1"
    const val ROOM = "2.3.0"
    const val GREEN_DAO = "3.3.0"
    const val CRYPTO = "1.0.0-rc03"
    const val ARCH_CORE_RUNTIME = "2.0.1"
    const val TIMBER = "4.7.1"
    const val NAVIGATION = "2.3.5"
    const val ANDROIDX_LEGACY_SUPPORT = "1.0.0"
    const val glide = "4.11.0"
    const val MULTIDEX = "2.0.1"
    const val VECTOR_DRAWABLE = "1.1.0"
    const val BROKER_CODE = "1.1.1"
    const val BROKER_LIFE_CYCLE = "1.1.1"
    const val MAP = "18.0.0"
    const val RECYCLER_VIEW = "1.2.1"
    const val RX_JAVA = "2.2.17"
    const val RX_ANDROID = "2.1.1"

    //    PLUGINS
    const val GRADLE = "4.1.1"
    const val KOTLIN = "1.5.20"
    const val GREEN_DAO_PLUGIN = "3.3.0"
    const val GOOGLE_SERVICES_PLUGIN = "4.3.10"
    const val CRASHLYTICS_PLUGIN = "2.8.0"
}
